parameters:
#    hu_frontend.example.class: HU\FrontendBundle\Example

services:
#    hu_frontend.example:
#        class: %hu_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
